FeroCourse-main/Areas/Admin/Controllers/CategoryController.cs
using FeroCourse.Data;
using FeroCourse.Data.Entities;
using FeroCourse.Data.ViewModels;
using FeroCourse.ServicesInterface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;

namespace FeroCourse.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _dbcontext;

        public CategoryController(ApplicationDbContext dbcontext)
        {
            _dbcontext = dbcontext;
            
        }
        [HttpGet]
        public IActionResult CategoryCreate()
        {
            var datalist = _dbcontext.Categorys.Select(x => new CategoryVM
            {
                CategoryId = x.CategoryId,
                CategoryName = x.CategoryName,
                CategoryDescription = x.CategoryDescription,
                CategoryIsActive = x.CategoryIsActive,
                
            }).ToList();

            return View(datalist);
            
        }

        [HttpPost]
        public IActionResult CategoryCreate(CategoryVM viewmodel)
        {
            var data = new Category();

            data.CategoryName = viewmodel.CategoryName;
            
            data.CategoryDescription = viewmodel.CategoryDescription;
            data.CategoryIsActive = viewmodel.CategoryIsActive;

            _dbcontext.Categorys.Add(data);
            _dbcontext.SaveChanges();
            return RedirectToAction("CategoryCreate");
        }

        [HttpGet]
        public IActionResult GetCategory(int id)
        {
            var data = _dbcontext.Categorys
                    .Where(x => x.CategoryId == id)
                    .Select(x => new CategoryVM
                    {
                        CategoryId = x.CategoryId,
                        CategoryName = x.CategoryName,
                        CategoryDescription = x.CategoryDescription,
                        CategoryIsActive = x.CategoryIsActive,

                    }).FirstOrDefault();

            if (data == null)
                return NotFound();

            return Json(data);

            
        }

        [HttpPost]
        public IActionResult CategoryEdit(CategoryVM viewmodel)
        {

            var data = new Category();

            data.CategoryId = viewmodel.CategoryId;
            data.CategoryName = viewmodel.CategoryName;
            data.CategoryDescription = viewmodel.CategoryDescription;
            data.CategoryIsActive = viewmodel.CategoryIsActive;

            _dbcontext.Categorys.Update(data);
            _dbcontext.SaveChanges();

            return Json("");
        }

        [HttpPost]
        public IActionResult CategoryDelete(int id)
        {
            if (id == 0)
            {
                return Json("Category not valid");
            }
            var checkdata = _dbcontext.Categorys.Where(x => x.CategoryId == id).FirstOrDefault();
            if (checkdata != null)
            {
                _dbcontext.Remove(checkdata);
                _dbcontext.SaveChanges();
                return Json("Deleted");
            }

            return BadRequest();

        }





    }
}

FeroCourse-main/Areas/Admin/Controllers/CourseController.cs
using FeroCourse.Data;
using FeroCourse.Data.Dtos;
using FeroCourse.Data.Entities;
using FeroCourse.ServicesInterface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

[Area("Admin")]
public class CourseController : Controller
{
    private readonly ApplicationDbContext _dbcontext;
    private readonly IFileUploadService _FileUploadService;

    public CourseController(ApplicationDbContext dbcontext, IFileUploadService FileUploadService)
    {
        _dbcontext = dbcontext;
        _FileUploadService = FileUploadService;
    }

    public IActionResult Index() => View();

    // ----------------- CREATE PAGE -----------------
    [HttpGet]
    public IActionResult CourseCreate()
    {
        LoadCategoryDropdown();
        return View(new CourseVM());
    }

    [HttpPost]
    public async Task<IActionResult> CourseCreate(CourseVM vm)
    {
        // Upload Image
        if (vm.Imagefile != null)
        {
            var imagepath = await _FileUploadService.UploadImageAsync(vm.Imagefile, "upload");
            if (!string.IsNullOrEmpty(imagepath))
            {
                vm.ThumbnailPath = imagepath;
            }
        }

        // Save Data
        var data = new Course
        {
            Title = vm.Title,
            Description = vm.Description,
            InstructorName = vm.InstructorName,
            Price = vm.Price,
            DiscountPrice = vm.DiscountPrice,
            ThumbnailPath = vm.ThumbnailPath,
            CategoryId = vm.CategoryId
        };

        _dbcontext.Courses.Add(data);
        _dbcontext.SaveChanges();

        // Reload dropdown before returning view
        LoadCategoryDropdown();

        return RedirectToAction("Courselist");
    }

    // ----------------- COURSE LIST -----------------
    public IActionResult Courselist()
    {
        var data = _dbcontext.Courses.Select(x => new CourseVM
        {
            CourseId = x.CourseId,
            Title = x.Title,
            Description = x.Description,
            InstructorName = x.InstructorName,
            Price = x.Price,
            DiscountPrice = x.DiscountPrice,
            ThumbnailPath = x.ThumbnailPath
        }).ToList();

        return View(data);
    }

    // ----------------- GET COURSE BY ID -----------------
    [HttpGet]
    public IActionResult GetCourse(int id)
    {
        var data = _dbcontext.Courses
            .Where(x => x.CourseId == id)
            .Select(x => new CourseVM
            {
                CourseId = x.CourseId,
                Title = x.Title,
                Description = x.Description,
                InstructorName = x.InstructorName,
                Price = x.Price,
                DiscountPrice = x.DiscountPrice,
                ThumbnailPath = "/" + x.ThumbnailPath
            }).FirstOrDefault();

        if (data == null)
            return NotFound();

        return Json(data);
    }

    // ----------------- EDIT COURSE -----------------
    [HttpPost]
    public async Task<IActionResult> CourseEditAsync([FromForm] CourseVM vm)
    {
        if (vm.CourseId == 0)
            return BadRequest("Invalid Course");

        var course = _dbcontext.Courses.FirstOrDefault(x => x.CourseId == vm.CourseId);
        if (course == null)
            return NotFound("Course not found");

        // New Image Upload
        if (vm.Imagefile != null)
        {
            var imagepath = await _FileUploadService.UploadImageAsync(vm.Imagefile, "upload");
            if (!string.IsNullOrEmpty(imagepath))
            {
                vm.ThumbnailPath = imagepath;
            }
        }
        else
        {
            vm.ThumbnailPath = course.ThumbnailPath; // keep old image
        }

        // Update Values
        course.Title = vm.Title;
        course.Description = vm.Description;
        course.InstructorName = vm.InstructorName;
        course.Price = vm.Price;
        course.DiscountPrice = vm.DiscountPrice;
        course.CategoryId = vm.CategoryId;
        course.ThumbnailPath = vm.ThumbnailPath;

        _dbcontext.Courses.Update(course);
        _dbcontext.SaveChanges();

        return Json("success");
    }

    // ----------------- DELETE COURSE -----------------
    [HttpPost]
    public IActionResult CourseDelete(int id)
    {
        var course = _dbcontext.Courses.FirstOrDefault(x => x.CourseId == id);
        if (course != null)
        {
            _dbcontext.Courses.Remove(course);
            _dbcontext.SaveChanges();
            return Ok();
        }
        return BadRequest();
    }

    // ----------------- LOAD DROPDOWN -----------------
    private void LoadCategoryDropdown()
    {
        var AllCategorydata = _dbcontext.Categorys.ToList();
        ViewBag.CategoryDropDown = AllCategorydata.Select(x =>
            new SelectListItem
            {
                Value = x.CategoryId.ToString(),
                Text = x.CategoryName
            }
        ).ToList();
    }
}

FeroCourse-main/Areas/Admin/Controllers/RoleController.cs
using System.Data;
using FeroCourse.Areas.Admin.ViewModels;
using FeroCourse.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.General;

namespace FeroCourse.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly UserManager<ApplicationUser> _userManager;


        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string RoleName)
        {

            if (!String.IsNullOrEmpty(RoleName))
            {
                bool isHave = await _roleManager.RoleExistsAsync(RoleName);
                if (!isHave)
                {
                    await _roleManager.CreateAsync(new IdentityRole(RoleName));
                    TempData["Message"] = "Success";
                    TempData["Type"] = "alert-success";
                    return View();
                }
            }
            TempData["Message"] = "Error";
            TempData["Type"] = "alert-danger";
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Assign()
        {
            var AllUserData = _userManager.Users.ToList();
            var AllRoles = _roleManager.Roles.ToList();

            var UserDropDown = AllUserData.Select(x => 
                    new SelectListItem {Value = x.Id,Text=x.Email }
             
            ).ToList();

            var RolesDropDown = AllRoles.Select(x =>
                   new SelectListItem { Value = x.Name, Text = x.NormalizedName }

           ).ToList();


            ViewBag.UserDropDown = UserDropDown;

            ViewBag.RolesDropDown = RolesDropDown;

            var userRoles = new List<UserRoleVM>();

            foreach (var user in AllUserData) {
                var CurrUserRoles = await _userManager.GetRolesAsync(user);
                userRoles.Add(new UserRoleVM
                {
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    Role = string.Join(",", CurrUserRoles)

                });


            }
            return View(userRoles);
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssignSubmit(string userId, string RoleName)
        {

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null || !await _roleManager.RoleExistsAsync(RoleName))
            {
                return View("Error");
            }

         

            var createRole = await _userManager.AddToRoleAsync(user, RoleName);

            if (createRole.Succeeded)
           

            return RedirectToAction("Assign");
            return View("Error");


        }

    }
}

FeroCourse-main/Areas/User/Controllers/DashboardController.cs
using FeroCourse.Areas.Admin.Controllers;
using FeroCourse.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Shared;

namespace FeroCourse.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = StaticMessages.User)]
    public class DashboardController : Controller
    {
        

        public IActionResult Index()
        {
            return View();
        }
    }
}

FeroCourse-main/Views/Shared/LandingPage.cshtml
<!-- Hero Section -->
<section class="hero">
    <div class="container">
        <h1>Learn Anytime, Anywhere</h1>
        <p>High-quality courses from expert instructors to help you grow your career and skills.</p>
        <a href="#" class="btn btn-main mt-3" style="color: #fff;">Browse Courses</a>
    </div>
</section>

<!-- Features Section -->
<section class="features text-center">
    <div class="container">
        <div class="row g-4">
            <div class="col-md-4">
                <div class="feature-card">
                    <h4>Expert Instructors</h4>
                    <p>Learn from professionals with years of industry experience.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature-card">
                    <h4>Flexible Learning</h4>
                    <p>Study at your own pace, anytime, and from any device.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature-card">
                    <h4>Certification</h4>
                    <p>Earn certificates to showcase your skills and advance your career.</p>
                </div>
            </div>
        </div>
    </div>
</section>

FeroCourse-main/Views/Shared/_AdminLayout.cshtml
@* _AdminLayout.cshtml *@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="">
    <meta name="author" content="Phoenixcoded" />
    <title>@ViewData["Title"] - Admin</title>

    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon" />

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/assets/css/style.css" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>
    <!-- [ Pre-loader ] end -->
    <!-- [ Navigation Menu ] start -->
    <nav class="pcoded-navbar">
        <div class="navbar-wrapper">
            <div class="navbar-content scroll-div">
                <div class="">
                    <div class="main-menu-header">
                        <img class="img-radius" src="~/assets/images/user/avatar-2.jpg" alt="User-Profile-Image">
                        <div class="user-details">
                            <span>@User.Identity.Name</span>
                            <div id="more-details">Admin<i class="fa fa-chevron-down m-l-5"></i></div>
                        </div>
                    </div>
                    <div class="collapse" id="nav-user-link">
                        <ul class="list-unstyled">
                            <li class="list-group-item">
                                <a asp-controller="Account" asp-action="Profile"><i class="feather icon-user m-r-5"></i>View Profile</a>
                            </li>
                            <li class="list-group-item">
                                <a asp-controller="Account" asp-action="Settings"><i class="feather icon-settings m-r-5"></i>Settings</a>
                            </li>
                            <li class="list-group-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="btn btn-link p-0"><i class="feather icon-log-out m-r-5"></i>Logout</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>

                <ul class="nav pcoded-inner-navbar">
                    <li class="nav-item pcoded-menu-caption"><label>Navigation</label></li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                            <span class="pcoded-mtext">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item pcoded-menu-caption"><label>Admin</label></li>
                    <li class="nav-item">
                        <a asp-controller="Category" asp-action="CategoryCreate" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-list"></i></span>
                            <span class="pcoded-mtext">Category</span>
                        </a>
                    </li>
                    <li class="nav-item pcoded-hasmenu">
                        <a href="#!" class="nav-link"><span class="pcoded-micon"><i class="feather icon-book"></i></span><span class="pcoded-mtext">Course</span></a>
                        <ul class="pcoded-submenu">
                            <li><a asp-area="Admin" asp-controller="Course" asp-action="CourseCreate">Create Course</a></li>
                            <li><a asp-area="Admin" asp-controller="Course" asp-action="Courselist">Course List</a></li>
                        </ul>
                    </li>
                   
                    <li class="nav-item pcoded-menu-caption"><label>Settings</label></li>
                    <li class="nav-item pcoded-hasmenu">
                        <a href="#!" class="nav-link"><span class="pcoded-micon"><i class="feather icon-layout"></i></span><span class="pcoded-mtext">Role</span></a>
                        <ul class="pcoded-submenu">
                            <li><a asp-area="Admin" asp-controller="Role" asp-action="Create">Create</a></li>
                            <li><a asp-area="Admin" asp-controller="Role" asp-action="Assign">Assign</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="LookupMang" asp-action="Index" class="nav-link">
                            <span class="pcoded-micon"><i class="feather icon-settings"></i></span>
                            <span class="pcoded-mtext">Lookup</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- [ Navigation Menu ] end -->
    <!-- [ Header ] start -->
    <header class="navbar pcoded-header navbar-expand-lg navbar-light header-dark">
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
            <a href="#!" class="b-brand">
                <img src="~/assets/images/logo.png" alt="Logo" class="logo">
                <img src="~/assets/images/logo-icon.png" alt="Logo Thumb" class="logo-thumb">
            </a>
            <a href="#!" class="mob-toggler"><i class="feather icon-more-vertical"></i></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#!" class="pop-search"><i class="feather icon-search"></i></a>
                    <div class="search-bar">
                        <input type="text" class="form-control border-0 shadow-none" placeholder="Search here">
                        <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            <i class="icon feather icon-bell"></i>
                            <span class="badge badge-pill badge-danger">5</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right notification">
                            @* Notifications placeholder *@
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown drp-user">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="feather icon-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-notification">
                            <div class="pro-head">
                                <img src="~/assets/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                                <span>@User.Identity.Name</span>
                                <form method="post" asp-controller="Account" asp-action="Logout" class="d-inline">
                                    <button type="submit" class="btn btn-link text-white p-0"><i class="feather icon-log-out"></i> Logout</button>
                                </form>
                            </div>
                            <ul class="pro-body">
                                <li><a asp-controller="Account" asp-action="Profile" class="dropdown-item"><i class="feather icon-user"></i> Profile</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </header>
    <!-- [ Header ] end -->
    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-content">
            @RenderBody()
        </div>
    </div>
    <!-- [ Main Content ] end -->
    <!-- Required JS -->
    <script src="~/assets/js/vendor-all.min.js"></script>
    <script src="~/assets/js/plugins/bootstrap.min.js"></script>
    <script src="~/assets/js/pcoded.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FeroCourse-main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FiroCourse</title>

    <!-- Local Bootstrap -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/layout.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>

<body>
    <div class="d-flex flex-column min-vh-100">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg py-3">
            <div class="container">
                <a class="navbar-brand fs-3 fw-bold" href="/Home/Index">Firo<span>Course</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navMenu">
                    <ul class="navbar-nav ms-auto align-items-lg-center gap-2">
                        <li class="nav-item">
                            <a class="nav-link text-secondary fw-medium" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary fw-medium" href="#">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary fw-medium" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary fw-medium" href="#">Contact</a>
                        </li>
                        <li class="nav-item ms-lg-3">
                            <a href="/Identity/Account/Login" class="btn btn-outline-primary btn-sm rounded-pill px-4">Login</a>
                        </li>
                        <li class="nav-item ms-lg-2">
                            <a href="/Identity/Account/Register" class="btn btn-primary btn-sm rounded-pill px-4">Register</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
        <!-- Dynamic Content Section -->
        <main class="flex-fill">
            @RenderBody()
        </main>



        <!-- Footer -->
        <footer class="mt-auto">
            <div class="container text-center">
                <p class="mb-2 fw-semibold">© 2025 FiroCourse. All rights reserved.</p>
                <a href="#">Privacy Policy</a> | <a href="#">Terms & Conditions</a>
            </div>
        </footer>
    </div>
    <!-- Scripts -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FeroCourse-main/Views/Shared/_UserLayout.cshtml
@using FeroCourse.Data.Entities
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FiroCourse</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/userlayout.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FeroCourse.styles.css" asp-append-version="true" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg py-3">
        <div class="container">
            <a class="navbar-brand fs-3 fw-bold" href="@Url.Action("Index", "Home")">Firo<span>Course</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navMenu">
                <ul class="navbar-nav ms-auto align-items-lg-center">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item"><a class="nav-link fw-semibold text-secondary" href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                        <li class="nav-item"><a class="nav-link fw-semibold text-secondary" href="@Url.Action("Courses", "Dashboard")">Courses</a></li>
                        <li class="nav-item"><a class="nav-link fw-semibold text-secondary" asp-action="Index" asp-controller="Profile" asp-area="User">Profile</a></li>
                        <li class="nav-item ms-lg-3">
                            <form method="post" asp-area="" asp-controller="Home" asp-action="Logout">
                                <button type="submit" class="btn btn-main">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link fw-semibold text-secondary" href="@Url.Page("/Account/Login", new { area = "Identity" })">Login</a></li>
                        <li class="nav-item ms-lg-3"><a class="btn btn-main" href="@Url.Page("/Account/Register", new { area = "Identity" })">Register</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Body -->
    <main>
        <section class="container py-5">
            @RenderBody()
        </section>
    </main>

    <!-- Footer -->
    <footer class="bg-light mt-auto">
        <div class="container text-center py-3">
            <p class="mb-0 fw-semibold">© 2025 FiroCourse. All rights reserved.</p>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>